In [1]:
import pymysql
import pandas as pd

In [2]:
conn = pymysql.connect(
    host="localhost",
    user="root",
    password="13849#Datasci",
    database="movie_analytics"
)

In [11]:
movies=pd.read_csv("movies_cleaned.csv")
cast=pd.read_csv("cast_cleaned.csv")
crew=pd.read_csv("crew_cleaned.csv")
genres=pd.read_csv("genres_cleaned.csv")
movie_genres=pd.read_csv("movie_genres_cleaned.csv")
movie_keywords=pd.read_csv("movie_keywords_cleaned.csv")

In [ ]:
query = """
SELECT
    m.title,
    m.release_date
FROM movies AS m
JOIN movie_genres AS mg
    ON m.movie_id = mg.movie_id
JOIN genres AS g
    ON mg.genre_id = g.genre_id
WHERE g.genre_name = 'Action'
  AND m.release_date >= '2016-01-01'
ORDER BY m.release_date ;
"""

result = pd.read_sql_query(query, conn)

result.head(10)

In [16]:
query = """
SELECT
    m.title,
    m.revenue,
    g.genre_name
FROM movies AS m
JOIN movie_genres AS mg
    ON m.movie_id = mg.movie_id
JOIN genres AS g
    ON mg.genre_id = g.genre_id
WHERE m.revenue IS NOT NULL
ORDER BY m.revenue DESC
LIMIT 10;
"""

result = pd.read_sql_query(query, conn)
result

C:\Users\dines\AppData\Local\Temp\ipykernel_25712\2392966820.py:16: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  result = pd.read_sql_query(query, conn)

                      title       revenue       genre_name
0                    Avatar  2.923706e+09        Adventure
1                    Avatar  2.923706e+09  Science Fiction
2                    Avatar  2.923706e+09           Action
3         Avengers: Endgame  2.799439e+09           Action
4         Avengers: Endgame  2.799439e+09        Adventure
5         Avengers: Endgame  2.799439e+09  Science Fiction
6  Avatar: The Way of Water  2.334485e+09           Action
7  Avatar: The Way of Water  2.334485e+09        Adventure
8  Avatar: The Way of Water  2.334485e+09  Science Fiction
9                   Titanic  2.264162e+09            Drama

In [3]:

query = """
SELECT
    g.genre_name,
    AVG(m.budget) AS average_budget,
    AVG(m.revenue) AS average_revenue
FROM movies AS m
JOIN movie_genres AS mg
    ON m.movie_id = mg.movie_id
JOIN genres AS g
    ON mg.genre_id = g.genre_id
GROUP BY g.genre_id, g.genre_name
ORDER BY average_revenue DESC;
"""

result = pd.read_sql_query(query, conn)
result

C:\Users\dines\AppData\Local\Temp\ipykernel_30508\154982000.py:15: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  result = pd.read_sql_query(query, conn)

         genre_name  average_budget  average_revenue
0         Adventure    1.093600e+08     3.902145e+08
1         Animation    8.336061e+07     3.597435e+08
2            Family    8.458426e+07     3.430968e+08
3   Science Fiction    9.525992e+07     3.235601e+08
4            Action    9.329457e+07     3.000547e+08
5           Fantasy    8.617784e+07     2.942975e+08
6            Comedy    5.256907e+07     2.113513e+08
7             Music    4.106939e+07     1.974526e+08
8           Romance    3.461113e+07     1.627896e+08
9          Thriller    4.938770e+07     1.605152e+08
10              War    5.332041e+07     1.563214e+08
11            Crime    4.456106e+07     1.448649e+08
12          History    5.257679e+07     1.404552e+08
13          Mystery    3.690394e+07     1.386307e+08
14            Drama    3.774313e+07     1.365055e+08
15          Western    5.236970e+07     1.348412e+08
16           Horror    2.517932e+07     1.098258e+08
17         TV Movie    2.800000e+06     9.365000e+02
18      Documentary    0.000000e+00     0.000000e+00

In [4]:

query = """
SELECT
    actor_name,
    COUNT(DISTINCT movie_id) AS movie_count
FROM cast
GROUP BY person_id, actor_name
ORDER BY movie_count DESC
LIMIT 10;
"""

result = pd.read_sql_query(query, conn)
result

C:\Users\dines\AppData\Local\Temp\ipykernel_30508\2073010875.py:11: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  result = pd.read_sql_query(query, conn)

           actor_name  movie_count
0   Samuel L. Jackson           39
1           Brad Pitt           38
2      Robert De Niro           38
3         Johnny Depp           37
4           Tom Hanks           33
5       Mark Wahlberg           32
6        Willem Dafoe           32
7          Tom Cruise           31
8  Scarlett Johansson           31
9      Morgan Freeman           31

In [5]:

query = """
SELECT
    person_id,
    person_name,
    COUNT(DISTINCT movie_id) AS movie_count
FROM crew
WHERE job = 'Director'
GROUP BY person_id, person_name
HAVING COUNT(DISTINCT movie_id) > 3
ORDER BY movie_count DESC;
"""

result = pd.read_sql_query(query, conn)
result

C:\Users\dines\AppData\Local\Temp\ipykernel_30508\2737677384.py:13: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  result = pd.read_sql_query(query, conn)

     person_id        person_name  movie_count
0          488   Steven Spielberg           27
1          510         Tim Burton           19
2          578       Ridley Scott           19
3         1032    Martin Scorsese           16
4           24    Robert Zemeckis           15
..         ...                ...          ...
212     138781      Robert Eggers            4
213    1056121       Ryan Coogler            4
214    1113116    Andy Muschietti            4
215    1179066           Wes Ball            4
216    1302082  David F. Sandberg            4

[217 rows x 3 columns]

In [6]:

query = """
SELECT
    keyword_name,
    COUNT(DISTINCT movie_id) AS movie_count
FROM movie_keywords
GROUP BY keyword_id, keyword_name
ORDER BY movie_count DESC
LIMIT 10;
"""

result = pd.read_sql_query(query, conn)
result

C:\Users\dines\AppData\Local\Temp\ipykernel_30508\3566799315.py:11: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  result = pd.read_sql_query(query, conn)

             keyword_name  movie_count
0  based on novel or book          449
1                  sequel          416
2    duringcreditsstinger          296
3     aftercreditsstinger          242
4                  murder          176
5     based on true story          166
6           new york city          161
7                 villain          160
8            3d animation          155
9          based on comic          154

In [7]:

query = """
SELECT
    title,
    budget,
    revenue
FROM movies
WHERE budget > (
    SELECT AVG(budget)
    FROM movies
    WHERE budget > 0
)
AND revenue < (
    SELECT AVG(revenue)
    FROM movies
    WHERE revenue > 0
)
AND budget > 0
AND revenue > 0
ORDER BY budget DESC;
"""

result = pd.read_sql_query(query, conn)
result

C:\Users\dines\AppData\Local\Temp\ipykernel_30508\3364070278.py:22: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  result = pd.read_sql_query(query, conn)

                                      title       budget      revenue
0                               The Marvels  274800000.0  206136825.0
1                                   Red One  250000000.0  185700759.0
2    Wake Up Dead Man: A Knives Out Mystery  210000000.0    4000000.0
3                         Wonder Woman 1984  200000000.0  169601036.0
4                                      Luca  200000000.0   51074773.0
..                                      ...          ...          ...
268                               Rambo III   63000000.0  189015611.0
269                         The Equalizer 2   62000000.0  190400157.0
270                                Æon Flux   62000000.0   53321673.0
271                                 Shooter   61000000.0   95700000.0
272                                  2 Guns   61000000.0  131940411.0

[273 rows x 3 columns]

In [8]:

query = """
SELECT DISTINCT
    c.actor_name,
    m.title AS movie_title,
    cr.person_name AS director_name
FROM `cast` AS c
JOIN crew AS cr
    ON c.movie_id = cr.movie_id
JOIN movies AS m
    ON c.movie_id = m.movie_id
WHERE cr.job = 'Director'
  AND cr.person_name = 'Christopher Nolan'
ORDER BY m.title, c.actor_name;
"""

result = pd.read_sql_query(query, conn)
result

C:\Users\dines\AppData\Local\Temp\ipykernel_30508\1370312868.py:16: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  result = pd.read_sql_query(query, conn)

             actor_name    movie_title      director_name
0        Christian Bale  Batman Begins  Christopher Nolan
1        Cillian Murphy  Batman Begins  Christopher Nolan
2           Gary Oldman  Batman Begins  Christopher Nolan
3          Katie Holmes  Batman Begins  Christopher Nolan
4          Ken Watanabe  Batman Begins  Christopher Nolan
..                  ...            ...                ...
105       Michael Caine   The Prestige  Christopher Nolan
106        Piper Perabo   The Prestige  Christopher Nolan
107        Rebecca Hall   The Prestige  Christopher Nolan
108    Samantha Mahurin   The Prestige  Christopher Nolan
109  Scarlett Johansson   The Prestige  Christopher Nolan

[110 rows x 3 columns]

In [9]:

query = """
SELECT
    g.genre_name,
    AVG(m.vote_average) AS average_rating,
    COUNT(DISTINCT m.movie_id) AS movie_count
FROM movies AS m
JOIN movie_genres AS mg
    ON m.movie_id = mg.movie_id
JOIN genres AS g
    ON mg.genre_id = g.genre_id
GROUP BY g.genre_id, g.genre_name
HAVING COUNT(DISTINCT m.movie_id) >= 20
ORDER BY average_rating DESC
LIMIT 1;
"""

result = pd.read_sql_query(query, conn)
result

C:\Users\dines\AppData\Local\Temp\ipykernel_30508\70806645.py:17: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  result = pd.read_sql_query(query, conn)

  genre_name  average_rating  movie_count
0        War        7.357576           85

In [10]:

query = """
SELECT
    m.title,
    COUNT(DISTINCT mk.keyword_id) AS keyword_count
FROM movies AS m
JOIN movie_keywords AS mk
    ON m.movie_id = mk.movie_id
GROUP BY m.movie_id, m.title
ORDER BY keyword_count DESC
LIMIT 10;
"""

result = pd.read_sql_query(query, conn)
result

C:\Users\dines\AppData\Local\Temp\ipykernel_30508\2163283887.py:13: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  result = pd.read_sql_query(query, conn)

                                        title  keyword_count
0                                     Smile 2             98
1                                     Taken 3             70
2                                 Silent Hill             63
3                              Twelve Monkeys             57
4              War for the Planet of the Apes             54
5                                 The Shining             52
6              Dawn of the Planet of the Apes             51
7                    How to Train Your Dragon             50
8  How to Train Your Dragon: The Hidden World             49
9                       Pacific Rim: Uprising             49